### ISSUE TITLE
很好用的东西！

### ISSUE THREAD

**Issue by pye52** [1217950746/Smile-Bookmarks#1]
可惜自己不会chrome开发，blog里发不了评论(友言的接口出错了？)…
这东西挺好用的，只是有时会打不开(可能是网络环境不太好)
支持一下~

**Comment by 1217950746** [comment]
可能外挂的友言评论，有Bug吧

**Comment by 1217950746** [comment]
Chrome插件开发，和普通网页并没有任何区别，Chrome提供了一些API，直接调用当作网页写就可以了
